add_newline = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = true

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[✗](bold red)"


[package]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[lua]
symbol= " "

[git_branch]
symbol= "  "

[git_status]
format ='([\[$all_status$ahead_behind\] ]($style))'
conflicted = "="
ahead = '[⇡$count ](bold green)'
behind = '[⇣$count ](bold green)'
deleted = "✘$count "
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](yellow)'
stashed = '[$count ](yellow)'
modified = '[!$count ](yellow)'
staged = '[+$count ](bold green)'
renamed = " $count "
untracked = '[?$count](red)'
style = "bold red"

[cmake]
symbol = "卑"

[golang]
symbol = "ﳑ "

[directory]
read_only = "  "
read_only_style = "red"
style = "bold green"
truncation_length = 1
truncation_symbol = "  ~/"
home_symbol = "  "

[custom.docker]
command = "docker version -f '{{.Server.Version}}' 2>/dev/null"
files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
style = "blue bold"
symbol = " v"
format = "via [$symbol$output]($style) "

