add_newline = false
[line_break]
disabled = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = true

[character]
    error_symbol = "[](bold red)"
    success_symbol = "[](bold green)"
    vicmd_symbol = "[](bold yellow)"
    format = "$symbol [|](bold bright-black) "



[package]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[lua]
symbol= " "

[git_branch]
symbol= "  "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
format ='([\[$all_status$ahead_behind\] ]($style))'
conflicted = "="
ahead = '[⇡$count ](bold green)'
behind = '[⇣$count ](bold green)'
deleted = "✘$count "
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](bold yellow)'
stashed = '[$count ](bold yellow)'
modified = '[!$count ](bold yellow)'
staged = '[+$count ](bold green)'
renamed = "»$count "
untracked = '[?$count](red)'
style = "bold red"

[cmake]
symbol = "卑"

[golang]
symbol = "ﳑ "

[custom.docker]
command = "docker version -f '{{.Server.Version}}' 2>/dev/null"
files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
style = "blue bold"
symbol = " v"
format = "via [$symbol$output]($style) "

